
export type Posiciones = "top" | "jg" | "mid" | "adc" | "sup";

export const posicionesOrdenadas: Posiciones[] = ["top", "jg", "mid", "adc", "sup"];

export type PlayerAssignment = {
  id: string;
  name: string;
  champion?: string;
};

export type Team = { [P in Posiciones]: PlayerAssignment };

type Champion = {
  name: string;
  roles: Posiciones[];
};

export const CHAMPIONS: Champion[] = [
    { name: "Aatrox", roles: ["top"] },
    { name: "Ahri", roles: ["mid"] },
    { name: "Akali", roles: ["mid", "top"] },
    { name: "Akshan", roles: ["mid", "adc"] },
    { name: "Alistar", roles: ["sup"] },
    { name: "Amumu", roles: ["jg", "sup"] },
    { name: "Anivia", roles: ["mid", "sup"] },
    { name: "Annie", roles: ["mid", "sup"] },
    { name: "Aphelios", roles: ["adc"] },
    { name: "Ashe", roles: ["adc", "sup"] },
    { name: "Aurelion Sol", roles: ["mid"] },
    { name: "Azir", roles: ["mid"] },
    { name: "Bard", roles: ["sup"] },
    { name: "Bel'Veth", roles: ["jg"] },
    { name: "Blitzcrank", roles: ["sup"] },
    { name: "Brand", roles: ["sup", "mid", "jg"] },
    { name: "Braum", roles: ["sup"] },
    { name: "Caitlyn", roles: ["adc"] },
    { name: "Camille", roles: ["top"] },
    { name: "Cassiopeia", roles: ["mid", "top"] },
    { name: "Cho'Gath", roles: ["top", "mid", "jg"] },
    { name: "Corki", roles: ["mid", "adc"] },
    { name: "Darius", roles: ["top", "jg"] },
    { name: "Diana", roles: ["jg", "mid"] },
    { name: "Draven", roles: ["adc"] },
    { name: "Dr. Mundo", roles: ["top", "jg"] },
    { name: "Ekko", roles: ["jg", "mid"] },
    { name: "Elise", roles: ["jg", "sup"] },
    { name: "Evelynn", roles: ["jg"] },
    { name: "Ezreal", roles: ["adc"] },
    { name: "Fiddlesticks", roles: ["jg", "sup", "top"] },
    { name: "Fiora", roles: ["top"] },
    { name: "Fizz", roles: ["mid"] },
    { name: "Galio", roles: ["mid", "sup"] },
    { name: "Gangplank", roles: ["top", "mid"] },
    { name: "Garen", roles: ["top", "jg"] },
    { name: "Gnar", roles: ["top"] },
    { name: "Gragas", roles: ["jg", "top", "mid"] },
    { name: "Graves", roles: ["jg", "top"] },
    { name: "Gwen", roles: ["top", "jg"] },
    { name: "Hecarim", roles: ["jg"] },
    { name: "Heimerdinger", roles: ["mid", "sup", "top"] },
    { name: "Illaoi", roles: ["top"] },
    { name: "Irelia", roles: ["top", "mid"] },
    { name: "Ivern", roles: ["jg"] },
    { name: "Janna", roles: ["sup"] },
    { name: "Jarvan IV", roles: ["jg", "top"] },
    { name: "Jax", roles: ["top", "jg"] },
    { name: "Jayce", roles: ["top", "mid"] },
    { name: "Jhin", roles: ["adc", "mid"] },
    { name: "Jinx", roles: ["adc"] },
    { name: "Kai'Sa", roles: ["adc", "mid"] },
    { name: "Kalista", roles: ["adc"] },
    { name: "Karma", roles: ["sup", "mid"] },
    { name: "Karthus", roles: ["jg"] },
    { name: "Kassadin", roles: ["mid"] },
    { name: "Katarina", roles: ["mid"] },
    { name: "Kayle", roles: ["top", "mid"] },
    { name: "Kayn", roles: ["jg"] },
    { name: "Kennen", roles: ["top"] },
    { name: "Kha'Zix", roles: ["jg"] },
    { name: "Kindred", roles: ["jg"] },
    { name: "Kled", roles: ["top"] },
    { name: "Kog'Maw", roles: ["adc", "mid"] },
    { name: "K'Sante", roles: ["top"] },
    { name: "LeBlanc", roles: ["mid"] },
    { name: "Lee Sin", roles: ["jg"] },
    { name: "Leona", roles: ["sup"] },
    { name: "Lillia", roles: ["jg", "top"] },
    { name: "Lissandra", roles: ["mid"] },
    { name: "Lucian", roles: ["adc", "mid"] },
    { name: "Lulu", roles: ["sup", "top"] },
    { name: "Lux", roles: ["mid", "sup"] },
    { name: "Malphite", roles: ["top", "sup", "mid"] },
    { name: "Malzahar", roles: ["mid"] },
    { name: "Maokai", roles: ["sup", "top", "jg"] },
    { name: "Master Yi", roles: ["jg"] },
    { name: "Milio", roles: ["sup"] },
    { name: "Miss Fortune", roles: ["adc", "sup"] },
    { name: "Wukong", roles: ["top", "jg"] },
    { name: "Mordekaiser", roles: ["top"] },
    { name: "Morgana", roles: ["sup", "jg"] },
    { name: "Naafiri", roles: ["mid", "jg"] },
    { name: "Nami", roles: ["sup"] },
    { name: "Nasus", roles: ["top"] },
    { name: "Nautilus", roles: ["sup", "jg"] },
    { name: "Neeko", roles: ["mid", "sup"] },
    { name: "Nidalee", roles: ["jg"] },
    { name: "Nilah", roles: ["adc"] },
    { name: "Nocturne", roles: ["jg"] },
    { name: "Nunu & Willump", roles: ["jg"] },
    { name: "Olaf", roles: ["top", "jg"] },
    { name: "Orianna", roles: ["mid"] },
    { name: "Ornn", roles: ["top"] },
    { name: "Pantheon", roles: ["top", "mid", "jg", "sup"] },
    { name: "Poppy", roles: ["top", "jg", "sup"] },
    { name: "Pyke", roles: ["sup"] },
    { name: "Qiyana", roles: ["mid", "jg"] },
    { name: "Quinn", roles: ["top"] },
    { name: "Rakan", roles: ["sup"] },
    { name: "Rammus", roles: ["jg"] },
    { name: "Rek'Sai", roles: ["jg"] },
    { name: "Rell", roles: ["sup"] },
    { name: "Renata Glasc", roles: ["sup"] },
    { name: "Renekton", roles: ["top"] },
    { name: "Rengar", roles: ["jg", "top"] },
    { name: "Riven", roles: ["top"] },
    { name: "Rumble", roles: ["top", "mid"] },
    { name: "Ryze", roles: ["mid", "top"] },
    { name: "Samira", roles: ["adc"] },
    { name: "Sejuani", roles: ["jg"] },
    { name: "Senna", roles: ["sup", "adc"] },
    { name: "Seraphine", roles: ["sup", "mid"] },
    { name: "Sett", roles: ["top", "sup"] },
    { name: "Shaco", roles: ["jg", "sup"] },
    { name: "Shen", roles: ["top", "sup"] },
    { name: "Shyvana", roles: ["jg", "top"] },
    { name: "Singed", roles: ["top"] },
    { name: "Sion", roles: ["top"] },
    { name: "Sivir", roles: ["adc"] },
    { name: "Skarner", roles: ["jg"] },
    { name: "Sona", roles: ["sup"] },
    { name: "Soraka", roles: ["sup"] },
    { name: "Swain", roles: ["sup", "mid", "top"] },
    { name: "Sylas", roles: ["mid", "jg"] },
    { name: "Syndra", roles: ["mid"] },
    { name: "Tahm Kench", roles: ["sup", "top"] },
    { name: "Taliyah", roles: ["mid", "jg"] },
    { name: "Talon", roles: ["mid", "jg"] },
    { name: "Taric", roles: ["sup"] },
    { name: "Teemo", roles: ["top"] },
    { name: "Thresh", roles: ["sup"] },
    { name: "Tristana", roles: ["adc", "mid"] },
    { name: "Trundle", roles: ["jg", "top"] },
    { name: "Tryndamere", roles: ["top"] },
    { name: "Twisted Fate", roles: ["mid"] },
    { name: "Twitch", roles: ["adc", "jg"] },
    { name: "Udyr", roles: ["jg", "top"] },
    { name: "Urgot", roles: ["top"] },
    { name: "Varus", roles: ["adc"] },
    { name: "Vayne", roles: ["adc", "top"] },
    { name: "Veigar", roles: ["mid"] },
    { name: "Vel'Koz", roles: ["mid", "sup"] },
    { name: "Vex", roles: ["mid"] },
    { name: "Vi", roles: ["jg"] },
    { name: "Viego", roles: ["jg"] },
    { name: "Viktor", roles: ["mid"] },
    { name: "Vladimir", roles: ["mid", "top"] },
    { name: "Volibear", roles: ["top", "jg"] },
    { name: "Warwick", roles: ["jg", "top"] },
    { name: "Xayah", roles: ["adc"] },
    { name: "Xerath", roles: ["mid", "sup"] },
    { name: "Xin Zhao", roles: ["jg"] },
    { name: "Yasuo", roles: ["mid", "top"] },
    { name: "Yone", roles: ["mid", "top"] },
    { name: "Yorick", roles: ["top"] },
    { name: "Yuumi", roles: ["sup"] },
    { name: "Zac", roles: ["jg"] },
    { name: "Zed", roles: ["mid"] },
    { name: "Zeri", roles: ["adc"] },
    { name: "Ziggs", roles: ["mid", "adc"] },
    { name: "Zilean", roles: ["sup"] },
    { name: "Zoe", roles: ["mid"] },
    { name: "Zyra", roles: ["sup", "mid"] },
    { name: "Mel", roles: ["sup", "mid", "adc"] },
    { name: "Yunara", roles: ["mid", "adc"] }
];